# Generated by Django 4.2.10 on 2025-07-24 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="product",
            new_name="products_pr_sku_ca0cdc_idx",
            old_name="products_pr_sku_58d1ab_idx",
        ),
        migrations.RenameIndex(
            model_name="product",
            new_name="products_pr_name_9ff0a3_idx",
            old_name="products_pr_name_1c2193_idx",
        ),
        migrations.RenameIndex(
            model_name="product",
            new_name="products_pr_price_9b1a5f_idx",
            old_name="products_pr_price_e96e35_idx",
        ),
        migrations.RenameIndex(
            model_name="product",
            new_name="products_pr_invento_437db4_idx",
            old_name="products_pr_invento_810e58_idx",
        ),
        migrations.RenameIndex(
            model_name="product",
            new_name="products_pr_updated_150263_idx",
            old_name="products_pr_updated_0e6ed4_idx",
        ),
    ]
